<?php

namespace AppBundle\Repository;

/**
 * FeedBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedBackRepository extends \Doctrine\ORM\EntityRepository
{
}
