<?php

namespace AppBundle\Repository;

/**
 * MediaCompositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaCompositionRepository extends \Doctrine\ORM\EntityRepository
{
}
