<?php

namespace AppBundle\Repository;

/**
 * MemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemesRepository extends \Doctrine\ORM\EntityRepository
{
}
