<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *@return Product[]
     */
   public  function findActive($id)
   {
       return $this
           ->createQueryBuilder('product')
           ->join('product.category','category')
           ->where('product.active=:active')
           ->andWhere('category.active=:active')
           ->setParameter('active',$id)
           ->getQuery()
           ->getResult()
           ;

   }

    public function findByCategory(Category $category)
    {
        return $this
            ->createQueryBuilder('product')
            ->where('product.active=:active')
            ->andWhere('product.category=:category')
            ->setParameter('active',1)
            ->setParameter('category',$category)
            ->getQuery()
            ->getResult()
            ;
    }
}


